package ru.bmstu.rk9.database;

import java.sql.SQLException;

/**
 * Created by farid on 4/7/17.
 */
public class TableManager {
    public void createTables() {
        try {
            Database.update("CREATE COLUMN TABLE tracker (" +
                    "id integer GENERATED BY DEFAULT AS IDENTITY," +
                    "created TIMESTAMP," +
                    "device VARCHAR(50)" +
                    ");");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
